version: "3"

services:
  timezone:
    container_name: timezone
    build:
      context: ../
      dockerfile: docker/timezone_service/Dockerfile
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      
  homeassistant_bridge:
    container_name: homeassistant_bridge
    build:
      context: ../
      dockerfile: docker/ha_bridge/Dockerfile
    restart: always
    network_mode: host

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0.7
    restart: always
    # As configured, MQTT will only accept connections from localhost!
    # ports: # not needed with host network mode
      # - 1883:1883
      # - 9001:9001
    network_mode: host
  
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2022.6.5
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./homeassistant:/config