/*THIS FILE IS AUTOMATICALLY GENERATED!*/
/*DO NOT EDIT THIS FILE!*/
#ifndef _KV_HASHES_H_
#define _KV_HASHES_H_
#include <inttypes.h>
#include "catbus_common.h"
#define $KV_meow_woof ((catbus_hash_t32)-0x3f73241c)
#define $KV_jeremy_rocks_ ((catbus_hash_t32)0x55f0d939)
#endif
